### ISSUE TITLE
something wrong in the argoverse-api1.1

### ISSUE THREAD

**Issue by fengmao31** [lsr12345/Auto-Trajectory-Prediction-Devkit#1]
```
python lanegcn_preprocess.py -i /home/fengmao/argoverse-api/train -m train
```
```
{'train': 205942, 'val': 39472, 'test': 78143, 'tiny': 64}
mode: train, dataset samples: 
Total number of sequences: 2
  0%|                                                                       | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "lanegcn_preprocess.py", line 640, in <module>
    main()
  File "lanegcn_preprocess.py", line 636, in main
    fromloader_save(train_loader, batch_size, save_path)
  File "lanegcn_preprocess.py", line 216, in fromloader_save
    for i, data in enumerate(tqdm(data_loader)):
  File "/home/fengmao/.local/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/fengmao/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/fengmao/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
    return self._process_data(data)
  File "/home/fengmao/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
    data.reraise()
  File "/home/fengmao/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/fengmao/miniconda3/envs/myenv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1622, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'CITY_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fengmao/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/fengmao/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/fengmao/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "lanegcn_preprocess.py", line 254, in __getitem__
    data = self.read_argo_data(idx)
  File "lanegcn_preprocess.py", line 306, in read_argo_data
    city = self.avl[idx].city
  File "/home/fengmao/argoverse-api/argoverse/data_loading/argoverse_forecasting_loader.py", line 58, in city
    _city: str = self.seq_df["CITY_NAME"].values[0]
  File "/home/fengmao/miniconda3/envs/myenv/lib/python3.8/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/fengmao/miniconda3/envs/myenv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1622, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'CITY_NAME'

```

**Comment by fengmao31** [comment]
```
python lanegcn_preprocess.py -i ~/argoverse-api/train/data -m train
```
